sudo: required

language: python

services:
        - docker

before_install:
        - docker pull amadeuschan/osproject
        - docker run -i -t amadeuschan/osproject

script:
        - python verify.py
